
FROM node:18


WORKDIR /backend


COPY package*.json ./


RUN npm install --legacy-peer-deps --include=optional


RUN apt-get update && apt-get install -y \
    libvips-dev \
    && rm -rf /var/lib/apt/lists/*


COPY . .


ENV PRISMA_QUERY_ENGINE_LIBRARY=/backend/node_modules/@prisma/client/libquery_engine-debian-openssl-3.0.x.so.node

RUN npx prisma generate


RUN npm run build


EXPOSE 3000

CMD ["node", "dist/index.js"]
